sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 031014
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:
    access-secret-key:
    bucket-name: sky-out-spirit

